### ISSUE TITLE
Nesta ignores theme’s .slim templates

### ISSUE THREAD

**Issue by agarzola** [gma/nesta#144]
After following [these instructions](http://nestacms.com/docs/design/templating-engines) to switch the templating engine to Slim, Nesta is throwing this error:

> No such file or directory - /Users/agarzola/.rvm/gems/ruby-1.9.2-p290/gems/nesta-0.9.13/views/page.slim

However, my theme does contains a `page.slim` template (I’ve renamed all of my theme’s templates to .slim), so it would seem that Nesta is ignoring my theme’s templates. I tried switching to Erb and did not get this error, so it seems to have something to do with Slim specifically.

[Here’s the app.rb](https://gist.github.com/agarzola/8290931) in my theme’s directory (`/themes/v2/app.rb`), in case it helps you spot any mistakes I may have made.

Thanks!

**Comment by gma** [comment]
This will have been fixed by 19ec573c06a9443091919e9142ded96e92fbf76c, which will be included in the next release.
