### ISSUE TITLE
Rack security vulnerability

### ISSUE THREAD

**Issue by etc** [gma/nesta#183]
Because of the fact that Nesta currently relies on an old version of Sinatra, which in turn relies on an old version of Rack, it is currently vulnerable to this: [https://github.com/advisories/GHSA-j6w9-fv6q-3q52](https://github.com/advisories/GHSA-j6w9-fv6q-3q52). Does anything stand in the way of updating the Sinatra dependency so that Nesta uses Rack version 2.1.4 or later?

**Comment by gma** [comment]
Thanks for that, I hadn't seen that CVE. I have done some work towards Rack 2 already, I'll brush it off and have a look.

**Comment by gma** [comment]
I've got a `rack-2` branch that appears to be working well. Do you fancy taking it for a spin before I release it as 0.12.0?

There have been a few significant upgrades since 0.11.1, so if you're interested and can spare the time I'd love to hear if you encounter any issues...

**Comment by gma** [comment]
This is how I've tested it on a couple of my sites, in their `Gemfile`:

```
gem 'nesta', git: 'https://github.com/gma/nesta', branch: 'rack-2'
```

**Comment by etc** [comment]
Thanks! I've run my site locally from that branch and all seems to work fine.

**Comment by gma** [comment]
Cheers @etc. I've just merged the branch to `master` and pushed out a new release (0.12.0).

**Comment by etc** [comment]
Brilliant, thanks.
