### ISSUE TITLE
Google Analytics Update

### ISSUE THREAD

**Issue by etc** [gma/nesta#193]
Google Universal Analytics standard properties will stop processing data on July 1, 2023. So that part of the code can be retired. I don't have the time right now to update Nesta to use the new [Google Analytics 4](https://support.google.com/analytics/answer/10759417) format instead. But I will do so at some later date if no one beats me to it!

**Comment by pelargir** [comment]
Do you want to try to support both at the same time, or would it be enough to just replace UA with GA4 entirely? A replacement wouldn't be backwards compatible for anyone still using UA, but UA will be gone by July.

**Comment by pelargir** [comment]
I've created https://github.com/gma/nesta/pull/201 which handles #2 above.

**Comment by gma** [comment]
I've just merged #201 ( :clap: ) so closing this.

Will be releasing 0.16.0 shortly…
