### ISSUE TITLE
Clash with Tilt 2.2.0

### ISSUE THREAD

**Issue by etc** [gma/nesta#197]
Something in the transition from Tilt 2.1.0 to 2.2.0 seems to break things. This is the error I get:

`~/.rvm/gems/ruby-3.2.2/bundler/gems/nesta-89f5c13c205d/lib/nesta/models/file_model.rb:2:in const_get: uninitialized constant Tilt::BlueClothTemplate (NameError)`

I'm manually specifying 2.1.0 in my Gemfile for now; not sure how simple a fix it is to get things working again.

**Comment by gma** [comment]
Hi Brad. Thanks for reporting that.

As you may have discovered, BlueCloth has been removed from Tilt in version 2.2.0. I've pushed a new commit to Nesta's main branch that will fix it if you update.

I've briefly tested your site locally with Tilt 2.2.0 and it seems fine. I'll release 0.15.0 later, but I'll leave it a few hours before I do in case you find something else wrong with it...

Cheers!

**Comment by etc** [comment]
Brilliant, I've updated my sites against the latest Nesta commit—both working no problem at all. Thank you!

**Comment by gma** [comment]
Awesome, cheers. I've just released 0.15.0.
