### ISSUE TITLE
Extensible formats system

### ISSUE THREAD

**Issue by lilith** [gma/nesta#74]
I'm looking at ways to give Nesta an extensible formats system so that plugins can define new content formats (or just add support for additional file extensions for the same ones). 

Tilt has a pretty refined interface for this, and while I don't see any way to piggyback on Tilt for heading and body parsing, I'm currently thinking of simply cloning Tilt's 'register' and 'prefer' API  for Nesta::Formats. See https://github.com/rtomayko/tilt/blob/master/lib/tilt.rb

Tilt's full API weighs in around 100 LOC.  That's a lot considering the code for parsing all the formats currently weighs  25 loc. 

Should I forego the full 'register'', 'prefer', & fallbacks, and simply have a last-registered-wins system, with at most 1 handler per file extension? Or should I stick with Tilt's API? 

Without a clean way to add formats I can't really migrate away from a custom nesta branch and start using plugins...

**Comment by gma** [comment]
I'm tidying up and closing issues that haven't seen any activity, or where it's not clear they're still required. If you still need/want this, feel free to re-open…
